name: Creating PR using Multi-Gitter

on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: test
        with:
          script: |
              echo "Hello"
